# Generated by Django 2.2 on 2019-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weekorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeStamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
